import os 
import sys
root = os.path.dirname(os.path.abspath(sys.argv[0]))
logfilen = logfile = root+'/simple_huckel.log'
logfile = open(logfilen,'w')
#sys.stdout = logfile

logfile.write(sys.argv[0])
logfile.flush()


website = "http://www.simplehuckel.com"
timebomb = (2009,6,1)
version = "0.2.0"
tool_tip_time = 4

#equivalnce threshold i.e. abs(a-b)<eps implies a=b
eps = 1.E-10


image_dir = root+'/images'
icon_file = image_dir+'/icon.bmp'
#name of subfolder where molecular and atomic data are held
data_dir_name = root+'/data'

#Atomic data file parameters
#atomic_data_file = os.path.join(os.path.dirname(__file__),data_dir_name,'atomic_data.yaml')
atomic_data_file = data_dir_name+'/atomic_data.yaml'
default_atomic_data_file = data_dir_name+'/default/atomic_data.yaml'

bond_data_file = data_dir_name+'/bond_data.yaml'
default_bond_data_file = data_dir_name+'/default/bond_data.yaml'

#atomic_data_file = 
h_delim = 'h'
k_delim = 'k'


#Num electrons
MIN_NUM_E = 0

DBL_CLICK_TIME = 0.50 #half a second
COLOUR_LIST = ["RED","BLUE","YELLOW","ORANGE","PURPLE",'THISTLE','SEASHELL','DODGERBLUE','BLACK','KHAKI', 'SKYBLUE', 'GREEN', 'CYAN','GOLDENROD','FIREBRICK','CHARTREUSE']*20
               
#t = ['SNOW', 'GHOST WHITE', 'GHOSTWHITE', 'WHITE SMOKE', 'WHITESMOKE', 'GAINSBORO', 'FLORAL WHITE', 'FLORALWHITE', 'OLD LACE', 'OLDLACE', 'LINEN', 'ANTIQUE WHITE', 'ANTIQUEWHITE', 'PAPAYA WHIP', 'PAPAYAWHIP', 'BLANCHED ALMOND', 'BLANCHEDALMOND', 'BISQUE', 'PEACH PUFF', 'PEACHPUFF', 'NAVAJO WHITE', 'NAVAJOWHITE', 'MOCCASIN', 'CORNSILK', 'IVORY', 'LEMON CHIFFON', 'LEMONCHIFFON', 'SEASHELL', 'HONEYDEW', 'MINT CREAM', 'MINTCREAM', 'AZURE', 'ALICE BLUE', 'ALICEBLUE', 'LAVENDER', 'LAVENDER BLUSH', 'LAVENDERBLUSH', 'MISTY ROSE', 'MISTYROSE', 'WHITE', 'BLACK', 'DARK SLATE GREY', 'DARKSLATEGREY', 'DIM GREY', 'DIMGREY', 'SLATE GREY', 'SLATEGREY', 'LIGHT SLATE GREY', 'LIGHTSLATEGREY', 'GREY', 'LIGHT GREY', 'LIGHTGREY', 'MIDNIGHT BLUE', 'MIDNIGHTBLUE', 'NAVY', 'NAVY BLUE', 'NAVYBLUE', 'CORNFLOWER BLUE', 'CORNFLOWERBLUE', 'DARK SLATE BLUE', 'DARKSLATEBLUE', 'SLATE BLUE', 'SLATEBLUE', 'MEDIUM SLATE BLUE', 'MEDIUMSLATEBLUE', 'LIGHT SLATE BLUE', 'LIGHTSLATEBLUE', 'MEDIUM BLUE', 'MEDIUMBLUE', 'ROYAL BLUE',
#     'ROYALBLUE', 'BLUE', 'DODGER BLUE', 'DODGERBLUE', 'DEEP SKY BLUE', 'DEEPSKYBLUE', 'SKY BLUE', 'SKYBLUE', 'LIGHT SKY BLUE', 'LIGHTSKYBLUE', 'STEEL BLUE', 'STEELBLUE', 'LIGHT STEEL BLUE', 'LIGHTSTEELBLUE', 'LIGHT BLUE', 'LIGHTBLUE', 'POWDER BLUE', 'POWDERBLUE', 'PALE TURQUOISE', 'PALETURQUOISE', 'DARK TURQUOISE', 'DARKTURQUOISE', 'MEDIUM TURQUOISE', 'MEDIUMTURQUOISE', 'TURQUOISE', 'CYAN', 'LIGHT CYAN', 'LIGHTCYAN', 'CADET BLUE', 'CADETBLUE', 'MEDIUM AQUAMARINE', 'MEDIUMAQUAMARINE', 'AQUAMARINE', 'DARK GREEN', 'DARKGREEN', 'DARK OLIVE GREEN', 'DARKOLIVEGREEN', 'DARK SEA GREEN', 'DARKSEAGREEN', 'SEA GREEN', 'SEAGREEN', 'MEDIUM SEA GREEN', 'MEDIUMSEAGREEN', 'LIGHT SEA GREEN', 'LIGHTSEAGREEN', 'PALE GREEN', 'PALEGREEN', 'SPRING GREEN', 'SPRINGGREEN', 'LAWN GREEN', 'LAWNGREEN', 'GREEN', 'CHARTREUSE', 'MEDIUM SPRING GREEN', 'MEDIUMSPRINGGREEN', 'GREEN YELLOW', 'GREENYELLOW', 'LIME GREEN', 'LIMEGREEN', 'YELLOW GREEN', 'YELLOWGREEN', 'FOREST GREEN', 'FORESTGREEN', 'OLIVE DRAB', 'OLIVEDRAB', 'DA
#     RK KHAKI', 'DARKKHAKI', 'KHAKI', 'PALE GOLDENROD', 'PALEGOLDENROD', 'LIGHT GOLDENROD YELLOW', 'LIGHTGOLDENRODYELLOW', 'LIGHT YELLOW', 'LIGHTYELLOW', 'YELLOW', 'GOLD', 'LIGHT GOLDENROD', 'LIGHTGOLDENROD', 'GOLDENROD', 'DARK GOLDENROD', 'DARKGOLDENROD', 'ROSY BROWN', 'ROSYBROWN', 'INDIAN RED', 'INDIANRED', 'SADDLE BROWN', 'SADDLEBROWN', 'SIENNA', 'PERU', 'BURLYWOOD', 'BEIGE', 'WHEAT', 'SANDY BROWN', 'SANDYBROWN', 'TAN', 'CHOCOLATE', 'FIREBRICK', 'BROWN', 'DARK SALMON', 'DARKSALMON', 'SALMON', 'LIGHT SALMON', 'LIGHTSALMON', 'ORANGE', 'DARK ORANGE', 'DARKORANGE', 'CORAL', 'LIGHT CORAL', 'LIGHTCORAL', 'TOMATO', 'ORANGE RED', 'ORANGERED', 'RED', 'HOT PINK', 'HOTPINK', 'DEEP PINK', 'DEEPPINK', 'PINK', 'LIGHT PINK', 'LIGHTPINK', 'PALE VIOLET RED', 'PALEVIOLETRED', 'MAROON', 'MEDIUM VIOLET RED', 'MEDIUMVIOLETRED', 'VIOLET RED', 'VIOLETRED', 'MAGENTA', 'VIOLET', 'PLUM', 'ORCHID', 'MEDIUM ORCHID', 'MEDIUMORCHID', 'DARK ORCHID', 'DARKORCHID', 'DARK VIOLET', 'DARKVIOLET', 'BLUE VIOLET', 'BLUEVIOLET
#     ', 'PURPLE', 'MEDIUM PURPLE', 'MEDIUMPURPLE', 'THISTLE', 'SNOW1', 'SNOW2', 'SNOW3', 'SNOW4', 'SEASHELL1', 'SEASHELL2', 'SEASHELL3', 'SEASHELL4', 'ANTIQUEWHITE1', 'ANTIQUEWHITE2', 'ANTIQUEWHITE3', 'ANTIQUEWHITE4', 'BISQUE1', 'BISQUE2', 'BISQUE3', 'BISQUE4', 'PEACHPUFF1', 'PEACHPUFF2', 'PEACHPUFF3', 'PEACHPUFF4', 'NAVAJOWHITE1', 'NAVAJOWHITE2', 'NAVAJOWHITE3', 'NAVAJOWHITE4', 'LEMONCHIFFON1', 'LEMONCHIFFON2', 'LEMONCHIFFON3', 'LEMONCHIFFON4', 'CORNSILK1', 'CORNSILK2', 'CORNSILK3', 'CORNSILK4', 'IVORY1', 'IVORY2', 'IVORY3', 'IVORY4', 'HONEYDEW1', 'HONEYDEW2', 'HONEYDEW3', 'HONEYDEW4', 'LAVENDERBLUSH1', 'LAVENDERBLUSH2', 'LAVENDERBLUSH3', 'LAVENDERBLUSH4', 'MISTYROSE1', 'MISTYROSE2', 'MISTYROSE3', 'MISTYROSE4', 'AZURE1', 'AZURE2', 'AZURE3', 'AZURE4', 'SLATEBLUE1', 'SLATEBLUE2', 'SLATEBLUE3', 'SLATEBLUE4', 'ROYALBLUE1', 'ROYALBLUE2', 'ROYALBLUE3', 'ROYALBLUE4', 'BLUE1', 'BLUE2', 'BLUE3', 'BLUE4', 'DODGERBLUE1', 'DODGERBLUE2', 'DODGERBLUE3', 'DODGERBLUE4', 'STEELBLUE1', 'STEELBLUE2', 'STEELB
#     LUE3', 'STEELBLUE4', 'DEEPSKYBLUE1', 'DEEPSKYBLUE2', 'DEEPSKYBLUE3', 'DEEPSKYBLUE4', 'SKYBLUE1', 'SKYBLUE2', 'SKYBLUE3', 'SKYBLUE4', 'LIGHTSKYBLUE1', 'LIGHTSKYBLUE2', 'LIGHTSKYBLUE3', 'LIGHTSKYBLUE4', 'LIGHTSTEELBLUE1', 'LIGHTSTEELBLUE2', 'LIGHTSTEELBLUE3', 'LIGHTSTEELBLUE4', 'LIGHTBLUE1', 'LIGHTBLUE2', 'LIGHTBLUE3', 'LIGHTBLUE4', 'LIGHTCYAN1', 'LIGHTCYAN2', 'LIGHTCYAN3', 'LIGHTCYAN4', 'PALETURQUOISE1', 'PALETURQUOISE2', 'PALETURQUOISE3', 'PALETURQUOISE4', 'CADETBLUE1', 'CADETBLUE2', 'CADETBLUE3', 'CADETBLUE4', 'TURQUOISE1', 'TURQUOISE2', 'TURQUOISE3', 'TURQUOISE4', 'CYAN1', 'CYAN2', 'CYAN3', 'CYAN4', 'AQUAMARINE1', 'AQUAMARINE2', 'AQUAMARINE3', 'AQUAMARINE4', 'DARKSEAGREEN1', 'DARKSEAGREEN2', 'DARKSEAGREEN3', 'DARKSEAGREEN4', 'SEAGREEN1', 'SEAGREEN2', 'SEAGREEN3', 'SEAGREEN4', 'PALEGREEN1', 'PALEGREEN2', 'PALEGREEN3', 'PALEGREEN4', 'SPRINGGREEN1', 'SPRINGGREEN2', 'SPRINGGREEN3', 'SPRINGGREEN4', 'GREEN1', 'GREEN2', 'GREEN3', 'GREEN4', 'CHARTREUSE1', 'CHARTREUSE2', 'CHARTREUSE3', 'CHART
#     REUSE4', 'OLIVEDRAB1', 'OLIVEDRAB2', 'OLIVEDRAB3', 'OLIVEDRAB4', 'DARKOLIVEGREEN1', 'DARKOLIVEGREEN2', 'DARKOLIVEGREEN3', 'DARKOLIVEGREEN4', 'KHAKI1', 'KHAKI2', 'KHAKI3', 'KHAKI4', 'LIGHTGOLDENROD1', 'LIGHTGOLDENROD2', 'LIGHTGOLDENROD3', 'LIGHTGOLDENROD4', 'LIGHTYELLOW1', 'LIGHTYELLOW2', 'LIGHTYELLOW3', 'LIGHTYELLOW4', 'YELLOW1', 'YELLOW2', 'YELLOW3', 'YELLOW4', 'GOLD1', 'GOLD2', 'GOLD3', 'GOLD4', 'GOLDENROD1', 'GOLDENROD2', 'GOLDENROD3', 'GOLDENROD4', 'DARKGOLDENROD1', 'DARKGOLDENROD2', 'DARKGOLDENROD3', 'DARKGOLDENROD4', 'ROSYBROWN1', 'ROSYBROWN2', 'ROSYBROWN3', 'ROSYBROWN4', 'INDIANRED1', 'INDIANRED2', 'INDIANRED3', 'INDIANRED4', 'SIENNA1', 'SIENNA2', 'SIENNA3', 'SIENNA4', 'BURLYWOOD1', 'BURLYWOOD2', 'BURLYWOOD3', 'BURLYWOOD4', 'WHEAT1', 'WHEAT2', 'WHEAT3', 'WHEAT4', 'TAN1', 'TAN2', 'TAN3', 'TAN4', 'CHOCOLATE1', 'CHOCOLATE2', 'CHOCOLATE3', 'CHOCOLATE4', 'FIREBRICK1', 'FIREBRICK2', 'FIREBRICK3', 'FIREBRICK4', 'BROWN1', 'BROWN2', 'BROWN3', 'BROWN4', 'SALMON1', 'SALMON2', 'SALMON3', 'S
#     ALMON4', 'LIGHTSALMON1', 'LIGHTSALMON2', 'LIGHTSALMON3', 'LIGHTSALMON4', 'ORANGE1', 'ORANGE2', 'ORANGE3', 'ORANGE4', 'DARKORANGE1', 'DARKORANGE2', 'DARKORANGE3', 'DARKORANGE4', 'CORAL1', 'CORAL2', 'CORAL3', 'CORAL4', 'TOMATO1', 'TOMATO2', 'TOMATO3', 'TOMATO4', 'ORANGERED1', 'ORANGERED2', 'ORANGERED3', 'ORANGERED4', 'RED1', 'RED2', 'RED3', 'RED4', 'DEEPPINK1', 'DEEPPINK2', 'DEEPPINK3', 'DEEPPINK4', 'HOTPINK1', 'HOTPINK2', 'HOTPINK3', 'HOTPINK4', 'PINK1', 'PINK2', 'PINK3', 'PINK4', 'LIGHTPINK1', 'LIGHTPINK2', 'LIGHTPINK3', 'LIGHTPINK4', 'PALEVIOLETRED1', 'PALEVIOLETRED2', 'PALEVIOLETRED3', 'PALEVIOLETRED4', 'MAROON1', 'MAROON2', 'MAROON3', 'MAROON4', 'VIOLETRED1', 'VIOLETRED2', 'VIOLETRED3', 'VIOLETRED4', 'MAGENTA1', 'MAGENTA2', 'MAGENTA3', 'MAGENTA4', 'ORCHID1', 'ORCHID2', 'ORCHID3', 'ORCHID4', 'PLUM1', 'PLUM2', 'PLUM3', 'PLUM4', 'MEDIUMORCHID1', 'MEDIUMORCHID2', 'MEDIUMORCHID3', 'MEDIUMORCHID4', 'DARKORCHID1', 'DARKORCHID2', 'DARKORCHID3', 'DARKORCHID4', 'PURPLE1', 'PURPLE2', 'PURPLE3'
#     , 'PURPLE4', 'MEDIUMPURPLE1', 'MEDIUMPURPLE2', 'MEDIUMPURPLE3', 'MEDIUMPURPLE4', 'THISTLE1', 'THISTLE2', 'THISTLE3', 'THISTLE4', 'GREY0', 'GREY1', 'GREY2', 'GREY3', 'GREY4', 'GREY5', 'GREY6', 'GREY7', 'GREY8', 'GREY9', 'GREY10', 'GREY11', 'GREY12', 'GREY13', 'GREY14', 'GREY15', 'GREY16', 'GREY17', 'GREY18', 'GREY19', 'GREY20', 'GREY21', 'GREY22', 'GREY23', 'GREY24', 'GREY25', 'GREY26', 'GREY27', 'GREY28', 'GREY29', 'GREY30', 'GREY31', 'GREY32', 'GREY33', 'GREY34', 'GREY35', 'GREY36', 'GREY37', 'GREY38', 'GREY39', 'GREY40', 'GREY41', 'GREY42', 'GREY43', 'GREY44', 'GREY45', 'GREY46', 'GREY47', 'GREY48', 'GREY49', 'GREY50', 'GREY51', 'GREY52', 'GREY53', 'GREY54', 'GREY55', 'GREY56', 'GREY57', 'GREY58', 'GREY59', 'GREY60', 'GREY61', 'GREY62', 'GREY63', 'GREY64', 'GREY65', 'GREY66', 'GREY67', 'GREY68', 'GREY69', 'GREY70', 'GREY71', 'GREY72', 'GREY73', 'GREY74', 'GREY75', 'GREY76', 'GREY77', 'GREY78', 'GREY79', 'GREY80', 'GREY81', 'GREY82', 'GREY83', 'GREY84', 'GREY85', 'GREY86', 'GREY87', '
#    GREY88', 'GREY89', 'GREY90', 'GREY91', 'GREY92', 'GREY93', 'GREY94', 'GREY95', 'GREY96', 'GREY97', 'GREY98', 'GREY99', 'GREY100', 'DARK GREY', 'DARKGREY', 'DARK BLUE', 'DARKBLUE', 'DARK CYAN', 'DARKCYAN', 'DARK MAGENTA', 'DARKMAGENTA', 'DARK RED', 'DARKRED', 'LIGHT GREEN', 'LIGHTGREEN']